dist: xenial
language: python
python:
  - "3.7"
deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true
    repo: tolstislon/pytest-pytestrail
    branch: master
    distributions: sdist bdist_wheel